# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-10"

[[extensions]]
name = "custom-banner"
handle = "custom-banner"
type = "ui_extension"
uid = "a11df538-16bc-a14a-1837-409727d7e91c41df6800"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"

[[extensions.targeting]]
target = "purchase.checkout.delivery-address.render-before"
module = "./src/Checkout.jsx"

[extensions.settings]
[[extensions.settings.fields]]
key = "heading"
type = "single_line_text_field"
name = "Banner heading"
description = "Enter a heading for the banner."
[[extensions.settings.fields]]
key = "description"
type = "single_line_text_field"
name = "Banner description"
description = "Enter a description for the banner."
[[extensions.settings.fields]]
key = "tone"
type = "single_line_text_field"
name = "Banner tone"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"info\", \"success\", \"warning\", \"critical\"]"
[[extensions.settings.fields]]
key = "collapsible"
type = "boolean"
name = "Show collapsible description."
description = "Display controls to expand or collapse the banner description."
