# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

api_version = "2026-07"

[[extensions]]
name = "order-action-customer-extension"
handle = "order-action-customer-extension"
type = "ui_extension"
uid = "5edbc7a4-ee57-3ed8-2751-65567e36c628f0a0f6dd"

[[extensions.targeting]]
module = "./src/MenuActionExtension.jsx"
target = "customer-account.order.action.menu-item.render"

[[extensions.targeting]]
module = "./src/MenuActionModalExtension.jsx"
target = "customer-account.order.action.render"

[[extensions.metafields]]
namespace = "$app"
key = "reportedProblem"
