# Fulfillment messaging on the order status page only.

api_version = "2026-07"

[[extensions]]
name = "Order status fulfillment"
handle = "inline-order-status-extension"
type = "ui_extension"
uid = "32a11a20-bd95-7c2c-3e2b-87d531155b9380d43c16"

[[extensions.targeting]]
module = "./src/FulfillmentDelivery.jsx"
target = "customer-account.order-status.fulfillment-details.render-after"

[[extensions.targeting]]
module = "./src/FulfillmentDelivery.jsx"
target = "customer-account.order-status.unfulfilled-items.render-after"
