# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
name = "inline-order-status-extension"
handle = "inline-order-status-extension"
type = "ui_extension"
uid = "32a11a20-bd95-7c2c-3e2b-87d531155b9380d43c16"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[[extensions.targeting]]
module = "./src/FulfillmentDelivery.jsx"
target = "customer-account.order-status.fulfillment-details.render-after"

[[extensions.targeting]]
module = "./src/FulfillmentDelivery.jsx"
target = "customer-account.order-status.unfulfilled-items.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true
