# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

api_version = "2026-07"

[[extensions]]
name = "survey-ui-extension"
handle = "survey-ui-extension"
type = "ui_extension"
uid = "122be68a-7f1c-777c-a2b8-3f193b92ab5bbfcf81eb"

[[extensions.targeting]]
module = "./src/ThankYouPageSurvey.jsx"
target = "purchase.thank-you.block.render"

[[extensions.targeting]]
module = "./src/OrderStatusPageSurvey.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
api_access = true
network_access = true
